namespace Utilities.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class config : DbMigration
    {
        public override void Up()
        {
            //RenameTable(name: "dbo.ApplicationPageApplicationRoles", newName: "ApplicationRolePage");
            //RenameTable(name: "dbo.ApplicationPageApplicationPages", newName: "ApplicationPageParents");
            //DropIndex("dbo.Devices", new[] { "ApplicationUser_Id" });
            //DropColumn("dbo.Devices", "UserId");
            //RenameColumn(table: "dbo.ApplicationPages", name: "Id", newName: "ApplicationPageId");
            //RenameColumn(table: "dbo.Devices", name: "ApplicationUser_Id", newName: "UserId");
            //RenameColumn(table: "dbo.ApplicationRolePage", name: "ApplicationPage_Id", newName: "ApplicationPageId");
            //RenameColumn(table: "dbo.ApplicationRolePage", name: "ApplicationRole_Id", newName: "ApplicationRoleId");
            //RenameColumn(table: "dbo.ApplicationPageParents", name: "ApplicationPage_Id", newName: "ApplicationPage_ApplicationPageId");
            //RenameColumn(table: "dbo.ApplicationPageParents", name: "ApplicationPage_Id1", newName: "ApplicationPage_ApplicationPageId1");
            //RenameIndex(table: "dbo.ApplicationPageParents", name: "IX_ApplicationPage_Id", newName: "IX_ApplicationPage_ApplicationPageId");
            //RenameIndex(table: "dbo.ApplicationPageParents", name: "IX_ApplicationPage_Id1", newName: "IX_ApplicationPage_ApplicationPageId1");
            //RenameIndex(table: "dbo.ApplicationRolePage", name: "IX_ApplicationRole_Id", newName: "IX_ApplicationRoleId");
            //RenameIndex(table: "dbo.ApplicationRolePage", name: "IX_ApplicationPage_Id", newName: "IX_ApplicationPageId");
           
            
            //DropPrimaryKey("dbo.ApplicationRolePage");
            AlterColumn("dbo.Branches", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "ArabicName", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "ArabicAddress", c => c.String(maxLength: 400));
            AlterColumn("dbo.Branches", "EnglishName", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "EnglishAddress", c => c.String(maxLength: 400));
            AlterColumn("dbo.Branches", "PhoneNumber", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "MapUrl", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "EmpedMapUrl", c => c.String(maxLength: 400));
            AlterColumn("dbo.Branches", "FaceBookLink", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "InstagramLink", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "TwitterLink", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "ArabicArea", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "EnglishArea", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "ArabicCity", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "EnglishCity", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "ArabicCountry", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "EnglishCountry", c => c.String(maxLength: 250));
            AlterColumn("dbo.Branches", "ImagePath", c => c.String(maxLength: 400));
            AlterColumn("dbo.AspNetUsers", "CrmUserId", c => c.String(maxLength: 250));
            AlterColumn("dbo.AspNetUsers", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.AspNetUsers", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.AspNetUsers", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.AspNetUsers", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Devices", "DeviceId", c => c.String(maxLength: 250));
            AlterColumn("dbo.Devices", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Devices", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Devices", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Devices", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.DbSqlQueries", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.DbSqlQueries", "Description", c => c.String(maxLength: 250));
            AlterColumn("dbo.DbSqlQueries", "Query", c => c.String(maxLength: 250));
            AlterColumn("dbo.DynamicTemplates", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.DynamicTemplates", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.DynamicTemplates", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.DynamicTemplates", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.DynamicTemplates", "Description", c => c.String(maxLength: 250));
            AlterColumn("dbo.paymentMethods", "BrandName", c => c.String(maxLength: 50));
            AlterColumn("dbo.paymentMethods", "EntityId", c => c.String(maxLength: 250));
            AlterColumn("dbo.paymentMethods", "EntityIdTest", c => c.String(maxLength: 250));
            AlterColumn("dbo.paymentMethods", "ImageUrl", c => c.String(maxLength: 400));
            AlterColumn("dbo.paymentMethods", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.paymentMethods", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.paymentMethods", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.paymentMethods", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "CustomerId", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "ContractId", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "EntityName", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "PaymentStatus", c => c.String(maxLength: 20));
            AlterColumn("dbo.PaymentTransactions", "PaymentStatusName", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "TransactionTypeName", c => c.String(maxLength: 50));
            AlterColumn("dbo.PaymentTransactions", "PaymentBrand", c => c.String(maxLength: 50));
            AlterColumn("dbo.PaymentTransactions", "RequestedPaymentBrand", c => c.String(maxLength: 50));
            AlterColumn("dbo.PaymentTransactions", "MerchantTransactionId", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "SourceOfFundsIssuer", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "TransactionAuthorizeCode", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "CardBinCountry", c => c.String(maxLength: 50));
            AlterColumn("dbo.PaymentTransactions", "CardHolder", c => c.String(maxLength: 100));
            AlterColumn("dbo.PaymentTransactions", "CustomerEmail", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "CustomerIPCountry", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.PaymentTransactions", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.ReceiptVouchers", "CustomerId", c => c.String(maxLength: 250));
            AlterColumn("dbo.ReceiptVouchers", "ContractId", c => c.String(maxLength: 250));
            AlterColumn("dbo.ReceiptVouchers", "ContractNumber", c => c.String(maxLength: 50));
            AlterColumn("dbo.ReceiptVouchers", "PaymentCode", c => c.String(maxLength: 50));
            AlterColumn("dbo.ReceiptVouchers", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.ReceiptVouchers", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.ReceiptVouchers", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.ReceiptVouchers", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.AspNetRoles", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.AspNetRoles", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.AspNetRoles", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.ApplicationPages", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.ApplicationPages", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.ApplicationPages", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.ApplicationPages", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Settings", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Settings", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Settings", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.Settings", "Name", c => c.String(nullable: false, maxLength: 250));
            AlterColumn("dbo.Settings", "Description", c => c.String(maxLength: 250));
            AlterColumn("dbo.StepDatas", "ControllerName", c => c.String(maxLength: 100));
            AlterColumn("dbo.StepDatas", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.StepDatas", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.StepDatas", "DeletedBy", c => c.String(maxLength: 250));

            AlterColumn("dbo.UrlShorteners", "Name", c => c.String(maxLength: 250));
            AlterColumn("dbo.UrlShorteners", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.UrlShorteners", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.UrlShorteners", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.UserNotifications", "Text", c => c.String(maxLength: 250));
            AlterColumn("dbo.UserNotifications", "DeviceId", c => c.String(maxLength: 250));
            AlterColumn("dbo.UserNotifications", "CrmUserId", c => c.String(maxLength: 250));
            AlterColumn("dbo.UserNotifications", "CreatedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.UserNotifications", "ModifiedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.UserNotifications", "DeletedBy", c => c.String(maxLength: 250));
            AlterColumn("dbo.UserNotifications", "Name", c => c.String(maxLength: 250));
         //   AddPrimaryKey("dbo.ApplicationRolePage", new[] { "ApplicationRoleId", "ApplicationPageId" });
          //  CreateIndex("dbo.Settings", "Name", unique: true, name: "Index");
        }
        
        public override void Down()
        {
            DropIndex("dbo.Settings", "Index");
            DropPrimaryKey("dbo.ApplicationRolePage");
            AlterColumn("dbo.UserNotifications", "Name", c => c.String());
            AlterColumn("dbo.UserNotifications", "DeletedBy", c => c.String());
            AlterColumn("dbo.UserNotifications", "ModifiedBy", c => c.String());
            AlterColumn("dbo.UserNotifications", "CreatedBy", c => c.String());
            AlterColumn("dbo.UserNotifications", "CrmUserId", c => c.String());
            AlterColumn("dbo.UserNotifications", "DeviceId", c => c.String());
            AlterColumn("dbo.UserNotifications", "Text", c => c.String());
            AlterColumn("dbo.UrlShorteners", "DeletedBy", c => c.String());
            AlterColumn("dbo.UrlShorteners", "ModifiedBy", c => c.String());
            AlterColumn("dbo.UrlShorteners", "CreatedBy", c => c.String());
            AlterColumn("dbo.UrlShorteners", "Name", c => c.String());

            AlterColumn("dbo.StepDatas", "DeletedBy", c => c.String());
            AlterColumn("dbo.StepDatas", "ModifiedBy", c => c.String());
            AlterColumn("dbo.StepDatas", "CreatedBy", c => c.String());
            AlterColumn("dbo.StepDatas", "ControllerName", c => c.String());
            AlterColumn("dbo.Settings", "Description", c => c.String());
            AlterColumn("dbo.Settings", "Name", c => c.String());
            AlterColumn("dbo.Settings", "DeletedBy", c => c.String());
            AlterColumn("dbo.Settings", "ModifiedBy", c => c.String());
            AlterColumn("dbo.Settings", "CreatedBy", c => c.String());
            AlterColumn("dbo.ApplicationPages", "DeletedBy", c => c.String());
            AlterColumn("dbo.ApplicationPages", "Name", c => c.String());
            AlterColumn("dbo.ApplicationPages", "ModifiedBy", c => c.String());
            AlterColumn("dbo.ApplicationPages", "CreatedBy", c => c.String());
            AlterColumn("dbo.AspNetRoles", "DeletedBy", c => c.String());
            AlterColumn("dbo.AspNetRoles", "ModifiedBy", c => c.String());
            AlterColumn("dbo.AspNetRoles", "CreatedBy", c => c.String());
            AlterColumn("dbo.ReceiptVouchers", "Name", c => c.String());
            AlterColumn("dbo.ReceiptVouchers", "DeletedBy", c => c.String());
            AlterColumn("dbo.ReceiptVouchers", "ModifiedBy", c => c.String());
            AlterColumn("dbo.ReceiptVouchers", "CreatedBy", c => c.String());
            AlterColumn("dbo.ReceiptVouchers", "PaymentCode", c => c.String());
            AlterColumn("dbo.ReceiptVouchers", "ContractNumber", c => c.String());
            AlterColumn("dbo.ReceiptVouchers", "ContractId", c => c.String());
            AlterColumn("dbo.ReceiptVouchers", "CustomerId", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "Name", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "DeletedBy", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "ModifiedBy", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "CreatedBy", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "CustomerIPCountry", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "CustomerEmail", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "CardHolder", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "CardBinCountry", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "TransactionAuthorizeCode", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "SourceOfFundsIssuer", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "MerchantTransactionId", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "RequestedPaymentBrand", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "PaymentBrand", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "TransactionTypeName", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "PaymentStatusName", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "PaymentStatus", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "EntityName", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "ContractId", c => c.String());
            AlterColumn("dbo.PaymentTransactions", "CustomerId", c => c.String());
            AlterColumn("dbo.paymentMethods", "Name", c => c.String());
            AlterColumn("dbo.paymentMethods", "DeletedBy", c => c.String());
            AlterColumn("dbo.paymentMethods", "ModifiedBy", c => c.String());
            AlterColumn("dbo.paymentMethods", "CreatedBy", c => c.String());
            AlterColumn("dbo.paymentMethods", "ImageUrl", c => c.String());
            AlterColumn("dbo.paymentMethods", "EntityIdTest", c => c.String());
            AlterColumn("dbo.paymentMethods", "EntityId", c => c.String());
            AlterColumn("dbo.paymentMethods", "BrandName", c => c.String());
            AlterColumn("dbo.DynamicTemplates", "Description", c => c.String());
            AlterColumn("dbo.DynamicTemplates", "Name", c => c.String());
            AlterColumn("dbo.DynamicTemplates", "DeletedBy", c => c.String());
            AlterColumn("dbo.DynamicTemplates", "ModifiedBy", c => c.String());
            AlterColumn("dbo.DynamicTemplates", "CreatedBy", c => c.String());
            AlterColumn("dbo.DbSqlQueries", "Query", c => c.String());
            AlterColumn("dbo.DbSqlQueries", "Description", c => c.String());
            AlterColumn("dbo.DbSqlQueries", "Name", c => c.String());
            AlterColumn("dbo.Devices", "Name", c => c.String());
            AlterColumn("dbo.Devices", "DeletedBy", c => c.String());
            AlterColumn("dbo.Devices", "ModifiedBy", c => c.String());
            AlterColumn("dbo.Devices", "CreatedBy", c => c.String());
            AlterColumn("dbo.Devices", "DeviceId", c => c.String());
            AlterColumn("dbo.AspNetUsers", "DeletedBy", c => c.String());
            AlterColumn("dbo.AspNetUsers", "Name", c => c.String());
            AlterColumn("dbo.AspNetUsers", "ModifiedBy", c => c.String());
            AlterColumn("dbo.AspNetUsers", "CreatedBy", c => c.String());
            AlterColumn("dbo.AspNetUsers", "CrmUserId", c => c.String());
            AlterColumn("dbo.Branches", "ImagePath", c => c.String());
            AlterColumn("dbo.Branches", "EnglishCountry", c => c.String());
            AlterColumn("dbo.Branches", "ArabicCountry", c => c.String());
            AlterColumn("dbo.Branches", "EnglishCity", c => c.String());
            AlterColumn("dbo.Branches", "ArabicCity", c => c.String());
            AlterColumn("dbo.Branches", "EnglishArea", c => c.String());
            AlterColumn("dbo.Branches", "ArabicArea", c => c.String());
            AlterColumn("dbo.Branches", "TwitterLink", c => c.String(maxLength: 4000));
            AlterColumn("dbo.Branches", "InstagramLink", c => c.String(maxLength: 4000));
            AlterColumn("dbo.Branches", "FaceBookLink", c => c.String(maxLength: 4000));
            AlterColumn("dbo.Branches", "EmpedMapUrl", c => c.String(maxLength: 4000));
            AlterColumn("dbo.Branches", "MapUrl", c => c.String(maxLength: 4000));
            AlterColumn("dbo.Branches", "PhoneNumber", c => c.String(maxLength: 4000));
            AlterColumn("dbo.Branches", "EnglishAddress", c => c.String(maxLength: 4000));
            AlterColumn("dbo.Branches", "EnglishName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Branches", "ArabicAddress", c => c.String(maxLength: 4000));
            AlterColumn("dbo.Branches", "ArabicName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Branches", "Name", c => c.String());
            AlterColumn("dbo.Branches", "DeletedBy", c => c.String());
            AlterColumn("dbo.Branches", "ModifiedBy", c => c.String());
            AlterColumn("dbo.Branches", "CreatedBy", c => c.String());
            AddPrimaryKey("dbo.ApplicationRolePage", new[] { "ApplicationPage_Id", "ApplicationRole_Id" });
            RenameIndex(table: "dbo.ApplicationRolePage", name: "IX_ApplicationPageId", newName: "IX_ApplicationPage_Id");
            RenameIndex(table: "dbo.ApplicationRolePage", name: "IX_ApplicationRoleId", newName: "IX_ApplicationRole_Id");
            RenameIndex(table: "dbo.ApplicationPageParents", name: "IX_ApplicationPage_ApplicationPageId1", newName: "IX_ApplicationPage_Id1");
            RenameIndex(table: "dbo.ApplicationPageParents", name: "IX_ApplicationPage_ApplicationPageId", newName: "IX_ApplicationPage_Id");
            RenameColumn(table: "dbo.ApplicationPageParents", name: "ApplicationPage_ApplicationPageId1", newName: "ApplicationPage_Id1");
            RenameColumn(table: "dbo.ApplicationPageParents", name: "ApplicationPage_ApplicationPageId", newName: "ApplicationPage_Id");
            RenameColumn(table: "dbo.ApplicationRolePage", name: "ApplicationRoleId", newName: "ApplicationRole_Id");
            RenameColumn(table: "dbo.ApplicationRolePage", name: "ApplicationPageId", newName: "ApplicationPage_Id");
            RenameColumn(table: "dbo.Devices", name: "UserId", newName: "ApplicationUser_Id");
            RenameColumn(table: "dbo.ApplicationPages", name: "ApplicationPageId", newName: "Id");
            AddColumn("dbo.Devices", "UserId", c => c.String(maxLength: 128));
            CreateIndex("dbo.Devices", "ApplicationUser_Id");
            RenameTable(name: "dbo.ApplicationPageParents", newName: "ApplicationPageApplicationPages");
            RenameTable(name: "dbo.ApplicationRolePage", newName: "ApplicationPageApplicationRoles");
        }
    }
}
