//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        public static string Christian {
            get {
                return ResourceManager.GetString("Christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        public static string ChristianFemale {
            get {
                return ResourceManager.GetString("ChristianFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorcee.
        /// </summary>
        public static string Divorcee {
            get {
                return ResourceManager.GetString("Divorcee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorcee.
        /// </summary>
        public static string DivorceeFemale {
            get {
                return ResourceManager.GetString("DivorceeFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string MarriedFemale {
            get {
                return ResourceManager.GetString("MarriedFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslim.
        /// </summary>
        public static string Muslim {
            get {
                return ResourceManager.GetString("Muslim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslim.
        /// </summary>
        public static string MuslimFemale {
            get {
                return ResourceManager.GetString("MuslimFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string SingleFemale {
            get {
                return ResourceManager.GetString("SingleFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widow.
        /// </summary>
        public static string Widow {
            get {
                return ResourceManager.GetString("Widow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widow.
        /// </summary>
        public static string WidowFemale {
            get {
                return ResourceManager.GetString("WidowFemale", resourceCulture);
            }
        }
    }
}
